import Head from 'next/head'
import Header from "../components/header";
import Nav from "../components/nav";
import Results from "../components/results";
import request from "../utils/request";

export default function Home({ results }) {
  return (
      <div>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico"/>
          </Head>
          <Header />

          <Nav />

          <Results results={results} />
      </div>
  )
}

export async function getServerSideProps(context) {
    const genre = context.query.genre;

    const req = await fetch(
        `https://api.themoviedb.org/3/${
            request[genre]?.url || request.fetchTrending.url
        }`
    ).then(res => res.json())

    return {
        props: {
            results: req.results
        }
    }
}
